# Generated by Django 5.2.8 on 2025-12-17 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Município"
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
            },
        ),
        migrations.CreateModel(
            name="NaturezaOcorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Natureza do Fato"
                    ),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("N", "Negativo"), ("P", "Positivo")],
                        max_length=1,
                        verbose_name="Aspecto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora_bruta",
                    models.CharField(
                        blank=True,
                        help_text="Formato DDHHMMMESAA (Ex: 151435DEZ25)",
                        max_length=15,
                        null=True,
                        verbose_name="Data/Hora Customizada",
                    ),
                ),
                (
                    "data_hora_fato",
                    models.DateTimeField(verbose_name="Data e Hora do Fato"),
                ),
                (
                    "relato_historico",
                    models.TextField(blank=True, verbose_name="Histórico Detalhado"),
                ),
                (
                    "resumo_cabecalho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resumo para Sumário"
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrencias",
                        to="rpi.naturezaocorrencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Envolvido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("V", "Vítima"),
                            ("A", "Autor"),
                            ("P", "Preso"),
                            ("T", "Testemunha"),
                            ("S", "Suspeito"),
                        ],
                        max_length=1,
                    ),
                ),
                ("idade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envolvidos",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da OPM")),
                (
                    "sigla",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Sigla da OPM"
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opms",
                        to="rpi.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPM",
                "verbose_name_plural": "OPMs",
                "unique_together": {("nome", "municipio")},
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="opm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.opm",
                verbose_name="OPM do Fato",
            ),
        ),
        migrations.CreateModel(
            name="RelatorioDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Início do Período (24h)"),
                ),
                ("data_fim", models.DateTimeField(verbose_name="Fim do Período (24h)")),
                (
                    "nr_relatorio",
                    models.PositiveIntegerField(verbose_name="Número do Relatório"),
                ),
                (
                    "ano_criacao",
                    models.PositiveIntegerField(verbose_name="Ano de Criação"),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_diarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Diário",
                "verbose_name_plural": "Relatórios Diários",
                "unique_together": {("nr_relatorio", "ano_criacao")},
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="relatorio_diario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.relatoriodiario",
            ),
        ),
    ]
