# Generated by Django 5.2.8 on 2025-12-31 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="MaterialApreendidoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tipo de Material"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Material Apreendido",
                "verbose_name_plural": "Tipos de Materiais Apreendidos",
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Município"
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
            },
        ),
        migrations.CreateModel(
            name="NaturezaOcorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Natureza do Fato"
                    ),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("N", "Negativo"), ("P", "Positivo")],
                        max_length=1,
                        verbose_name="Aspecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natureza da Ocorrência",
                "verbose_name_plural": "Naturezas de Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[("C", "Consumado"), ("T", "Tentado")],
                        default="C",
                        max_length=1,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "data_hora_bruta",
                    models.CharField(
                        blank=True,
                        help_text="Formato DDHHMMMESAA (Ex: 151435DEZ25)",
                        max_length=15,
                        null=True,
                        verbose_name="Data/Hora Customizada",
                    ),
                ),
                (
                    "data_hora_fato",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora do Fato (DB)"
                    ),
                ),
                (
                    "relato_historico",
                    models.TextField(blank=True, verbose_name="Histórico Detalhado"),
                ),
                (
                    "resumo_cabecalho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resumo para Sumário"
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Rua/Via"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rpi.instrumento",
                        verbose_name="Instrumento utilizado (para CVLI)",
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrencias",
                        to="rpi.naturezaocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="Envolvido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "antecedentes",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não"), ("I", "Não Informado")],
                        default="I",
                        max_length=1,
                        verbose_name="Antecedentes Criminais",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("V", "Vítima"),
                            ("A", "Autor"),
                            ("P", "Preso"),
                            ("T", "Testemunha"),
                            ("S", "Suspeito"),
                        ],
                        max_length=1,
                    ),
                ),
                ("idade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envolvidos",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envolvido",
                "verbose_name_plural": "Envolvidos",
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ocorrencias/imagens/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Legenda"
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="rpi.ocorrencia",
                        verbose_name="Ocorrência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Ocorrência",
                "verbose_name_plural": "Imagens da Ocorrência",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da OPM")),
                (
                    "sigla",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Sigla da OPM"
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opms",
                        to="rpi.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPM",
                "verbose_name_plural": "OPMs",
                "unique_together": {("nome", "municipio")},
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="opm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.opm",
                verbose_name="OPM do Fato",
            ),
        ),
        migrations.CreateModel(
            name="RelatorioDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_relatorio",
                    models.PositiveIntegerField(verbose_name="Número do Relatório"),
                ),
                (
                    "ano_criacao",
                    models.PositiveIntegerField(verbose_name="Ano de Criação"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Início do Período (24h)"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Período (24h)"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "finalizado",
                    models.BooleanField(
                        default=False, verbose_name="Relatório Finalizado"
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_diarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Diário",
                "verbose_name_plural": "Relatórios Diários",
                "unique_together": {("nr_relatorio", "ano_criacao")},
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="relatorio_diario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.relatoriodiario",
            ),
        ),
        migrations.CreateModel(
            name="Apreensao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Use vírgula para separar (Ex: 10.50 ou 1)",
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "material_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rpi.materialapreendidotipo",
                        verbose_name="Material Apreendido",
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apreensoes",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apreensão",
                "verbose_name_plural": "Apreensões",
                "unique_together": {("ocorrencia", "material_tipo")},
            },
        ),
    ]
