# Generated by Django 5.2.9 on 2026-01-22 01:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("records_deleted", models.PositiveIntegerField()),
                ("status", models.CharField(default="Sucesso", max_length=20)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Limpeza de Auditoria",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="Instrumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Instrumento",
                "verbose_name_plural": "Instrumentos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="MaterialApreendidoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Tipo de Material"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Material Apreendido",
                "verbose_name_plural": "Tipos de Materiais Apreendidos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Município"
                    ),
                ),
            ],
            options={
                "verbose_name": "Município",
                "verbose_name_plural": "Municípios",
            },
        ),
        migrations.CreateModel(
            name="NaturezaOcorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=255, unique=True, verbose_name="Fato"),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("N", "Negativo"), ("P", "Positivo")],
                        max_length=1,
                        verbose_name="Aspecto",
                    ),
                ),
                (
                    "tags_busca",
                    models.CharField(
                        blank=True,
                        help_text="Termos alternativos para pesquisa, separados por vírgula.",
                        max_length=500,
                        verbose_name="Tags de Busca (Opcional)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Natureza da Ocorrência",
                "verbose_name_plural": "Naturezas de Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="HistoricalInstrumento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Instrumento",
                "verbose_name_plural": "historical Instrumentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMaterialApreendidoTipo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tipo de Material"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de Material Apreendido",
                "verbose_name_plural": "historical Tipos de Materiais Apreendidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMunicipio",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nome do Município"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Município",
                "verbose_name_plural": "historical Municípios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNaturezaOcorrencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Fato"
                    ),
                ),
                (
                    "tipo_impacto",
                    models.CharField(
                        choices=[("N", "Negativo"), ("P", "Positivo")],
                        max_length=1,
                        verbose_name="Aspecto",
                    ),
                ),
                (
                    "tags_busca",
                    models.CharField(
                        blank=True,
                        help_text="Termos alternativos para pesquisa, separados por vírgula.",
                        max_length=500,
                        verbose_name="Tags de Busca (Opcional)",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Natureza da Ocorrência",
                "verbose_name_plural": "historical Naturezas de Ocorrências",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOPM",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da OPM")),
                (
                    "sigla",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Sigla da OPM"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical OPM",
                "verbose_name_plural": "historical OPMs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRelatorioDiario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nr_relatorio",
                    models.PositiveIntegerField(verbose_name="Número do Relatório"),
                ),
                (
                    "ano_criacao",
                    models.PositiveIntegerField(verbose_name="Ano de Criação"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Início do Período (24h)"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Período (24h)"
                    ),
                ),
                ("data_criacao", models.DateTimeField(blank=True, editable=False)),
                (
                    "finalizado",
                    models.BooleanField(
                        default=False, verbose_name="Relatório Finalizado"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Relatório Diário",
                "verbose_name_plural": "historical Relatórios Diários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[("C", "Consumado"), ("T", "Tentado")],
                        default="C",
                        max_length=1,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "data_hora_bruta",
                    models.CharField(
                        blank=True,
                        help_text="Formato DDHHMMMESAA (Ex: 151435DEZ25)",
                        max_length=15,
                        null=True,
                        verbose_name="Data/Hora Customizada",
                    ),
                ),
                (
                    "data_hora_fato",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora do Fato (DB)"
                    ),
                ),
                (
                    "relato_historico",
                    models.TextField(blank=True, verbose_name="Histórico Detalhado"),
                ),
                (
                    "resumo_cabecalho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resumo para Sumário"
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Rua/Via"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rpi.instrumento",
                        verbose_name="Instrumento utilizado (para CVLI)",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="rpi.municipio"
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ocorrencias",
                        to="rpi.naturezaocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
            },
        ),
        migrations.CreateModel(
            name="HistoricalEnvolvido",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("1", "RG"), ("2", "CPF")],
                        max_length=1,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "nr_documento",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="Nr"
                    ),
                ),
                (
                    "antecedentes",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não"), ("I", "N/D")],
                        default="I",
                        max_length=1,
                        verbose_name="Antec.",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("V", "Vítima"),
                            ("A", "Autor"),
                            ("M", "Menor Infrator"),
                            ("P", "Preso"),
                            ("T", "Testemunha"),
                            ("S", "Suspeito"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("idade", models.PositiveIntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Envolvido",
                "verbose_name_plural": "historical Envolvidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApreensao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Use vírgula para separar (Ex: 10.50 ou 1)",
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "descricao_adicional",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição Adicional",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.materialapreendidotipo",
                        verbose_name="Material Apreendido",
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Apreensão",
                "verbose_name_plural": "historical Apreensões",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Envolvido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("1", "RG"), ("2", "CPF")],
                        max_length=1,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "nr_documento",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="Nr"
                    ),
                ),
                (
                    "antecedentes",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não"), ("I", "N/D")],
                        default="I",
                        max_length=1,
                        verbose_name="Antec.",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("V", "Vítima"),
                            ("A", "Autor"),
                            ("M", "Menor Infrator"),
                            ("P", "Preso"),
                            ("T", "Testemunha"),
                            ("S", "Suspeito"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("idade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envolvidos",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envolvido",
                "verbose_name_plural": "Envolvidos",
            },
        ),
        migrations.CreateModel(
            name="Apreensao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Use vírgula para separar (Ex: 10.50 ou 1)",
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "descricao_adicional",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição Adicional",
                    ),
                ),
                (
                    "material_tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rpi.materialapreendidotipo",
                        verbose_name="Material Apreendido",
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apreensoes",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apreensão",
                "verbose_name_plural": "Apreensões",
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ocorrencias/imagens/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Legenda"
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="rpi.ocorrencia",
                        verbose_name="Ocorrência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Ocorrência",
                "verbose_name_plural": "Imagens da Ocorrência",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome da OPM")),
                (
                    "sigla",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Sigla da OPM"
                    ),
                ),
                (
                    "municipios",
                    models.ManyToManyField(
                        related_name="opms",
                        to="rpi.municipio",
                        verbose_name="Municípios Atendidos",
                    ),
                ),
            ],
            options={
                "verbose_name": "OPM",
                "verbose_name_plural": "OPMs",
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="opm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.opm",
            ),
        ),
        migrations.CreateModel(
            name="RelatorioDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nr_relatorio",
                    models.PositiveIntegerField(verbose_name="Número do Relatório"),
                ),
                (
                    "ano_criacao",
                    models.PositiveIntegerField(verbose_name="Ano de Criação"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Início do Período (24h)"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Período (24h)"
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "finalizado",
                    models.BooleanField(
                        default=False, verbose_name="Relatório Finalizado"
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="relatorios_diarios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Diário",
                "verbose_name_plural": "Relatórios Diários",
                "unique_together": {("nr_relatorio", "ano_criacao")},
            },
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="relatorio_diario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ocorrencias",
                to="rpi.relatoriodiario",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOcorrencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[("C", "Consumado"), ("T", "Tentado")],
                        default="C",
                        max_length=1,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "data_hora_bruta",
                    models.CharField(
                        blank=True,
                        help_text="Formato DDHHMMMESAA (Ex: 151435DEZ25)",
                        max_length=15,
                        null=True,
                        verbose_name="Data/Hora Customizada",
                    ),
                ),
                (
                    "data_hora_fato",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora do Fato (DB)"
                    ),
                ),
                (
                    "relato_historico",
                    models.TextField(blank=True, verbose_name="Histórico Detalhado"),
                ),
                (
                    "resumo_cabecalho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resumo para Sumário"
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Rua/Via"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.instrumento",
                        verbose_name="Instrumento utilizado (para CVLI)",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.municipio",
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.naturezaocorrencia",
                    ),
                ),
                (
                    "opm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.opm",
                    ),
                ),
                (
                    "relatorio_diario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.relatoriodiario",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ocorrência",
                "verbose_name_plural": "historical Ocorrências",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
