# Generated by Django 5.2.8 on 2025-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="tipo_acao",
            field=models.CharField(
                choices=[("C", "Consumado"), ("T", "Tentado")],
                default="C",
                max_length=1,
                verbose_name="Ação",
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="bairro",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="rua",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Rua/Via"
            ),
        ),
    ]
