# Generated by Django 5.2.8 on 2025-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatoriodiario",
            name="data_fim",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fim do Período (24h)"
            ),
        ),
    ]
