# Generated by Django 5.2.8 on 2025-12-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="data_hora_fato",
            field=models.DateTimeField(verbose_name="Data e Hora do Fato (DB)"),
        ),
    ]
