# Generated by Django 5.2.9 on 2026-01-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="apreensao",
            unique_together=set(),
        ),
    ]
