# Generated by Django 5.2.9 on 2026-01-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apreensao",
            name="unidade_medida",
            field=models.CharField(
                blank=True,
                choices=[("un", "un"), ("kg", "kg"), ("g", "g"), ("pe", "pé")],
                max_length=2,
                verbose_name="Unidade de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="unidade_medida",
            field=models.CharField(
                blank=True,
                choices=[("un", "un"), ("kg", "kg"), ("g", "g"), ("pe", "pé")],
                max_length=2,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
