# Generated by Django 5.2.9 on 2026-01-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0002_alter_apreensao_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="apreensao",
            name="descricao_adicional",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descrição Adicional",
            ),
        ),
    ]
