# Generated by Django 5.2.9 on 2025-12-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0002_alter_relatoriodiario_data_fim"),
    ]

    operations = [
        migrations.CreateModel(
            name="OcorrenciaImagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ocorrencias/imagens/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Legenda"
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="rpi.ocorrencia",
                        verbose_name="Ocorrência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da Ocorrência",
                "verbose_name_plural": "Imagens da Ocorrência",
                "ordering": ["id"],
            },
        ),
    ]
