# Generated by Django 5.2.8 on 2025-12-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0003_ocorrenciaimagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocorrencia",
            name="instrumento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ARMA_DE_FOGO", "ARMA DE FOGO"),
                    ("ARMA_BRANCA", "ARMA BRANCA"),
                    ("OBJETO_CONTUNDENTE", "OBJETO CONTUNDENTE"),
                    ("ASFIXIA", "ASFIXIA / ESTRANGULAMENTO"),
                    ("OUTROS", "OUTROS"),
                ],
                max_length=50,
                null=True,
                verbose_name="Instrumento utilizado (para CVLI)",
            ),
        ),
    ]
