# Generated by Django 5.2.9 on 2026-01-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0003_apreensao_descricao_adicional"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialapreendidotipo",
            options={
                "ordering": ["nome"],
                "verbose_name": "Tipo de Material Apreendido",
                "verbose_name_plural": "Tipos de Materiais Apreendidos",
            },
        ),
    ]
