# Generated by Django 5.2.9 on 2026-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0003_auto_20260123_1936"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apreensao",
            name="unidade_medida",
            field=models.CharField(
                blank=True,
                choices=[
                    ("un", "un"),
                    ("kg", "kg"),
                    ("g", "g"),
                    ("pe", "pé"),
                    ("R$", "Real (R$)"),
                    ("US$", "Dólar (US$)"),
                    ("€", "Euro (€)"),
                    ("ARS", "Peso Arg ($)"),
                ],
                max_length=3,
                verbose_name="Unidade de Medida",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapreensao",
            name="unidade_medida",
            field=models.CharField(
                blank=True,
                choices=[
                    ("un", "un"),
                    ("kg", "kg"),
                    ("g", "g"),
                    ("pe", "pé"),
                    ("R$", "Real (R$)"),
                    ("US$", "Dólar (US$)"),
                    ("€", "Euro (€)"),
                    ("ARS", "Peso Arg ($)"),
                ],
                max_length=3,
                verbose_name="Unidade de Medida",
            ),
        ),
    ]
