# Generated by Django 5.2.9 on 2026-01-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0004_alter_materialapreendidotipo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="naturezaocorrencia",
            name="tags_busca",
            field=models.CharField(
                blank=True,
                help_text="Termos alternativos para pesquisa, separados por vírgula.",
                max_length=500,
                verbose_name="Tags de Busca (Opcional)",
            ),
        ),
    ]
