# Generated by Django 5.2.9 on 2026-02-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0004_alter_apreensao_unidade_medida_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="envolvido",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="envolvidos/fotos/",
                verbose_name="Foto do Envolvido",
            ),
        ),
        migrations.AddField(
            model_name="historicalenvolvido",
            name="foto",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Foto do Envolvido"
            ),
        ),
    ]
