# Generated by Django 5.2.9 on 2026-01-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0005_naturezaocorrencia_tags_busca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="antecedentes",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não"), ("I", "Não Informado")],
                default="I",
                max_length=1,
                verbose_name="Antec. Criminais",
            ),
        ),
    ]
