# Generated by Django 5.2.9 on 2026-03-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0006_popular_tags_cvli"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[("1", "RG"), ("2", "CPF")],
                max_length=1,
                null=True,
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="historicalenvolvido",
            name="tipo_documento",
            field=models.CharField(
                blank=True,
                choices=[("1", "RG"), ("2", "CPF")],
                max_length=1,
                null=True,
                verbose_name="Documento",
            ),
        ),
    ]
