# Generated by Django 5.2.9 on 2026-01-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0007_alter_envolvido_tipo_participante"),
    ]

    operations = [
        migrations.AddField(
            model_name="envolvido",
            name="nr_documento",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="envolvido",
            name="tipo_documento",
            field=models.CharField(
                choices=[("1", "RG"), ("2", "CPF")],
                default=0,
                max_length=1,
                verbose_name="Documento",
            ),
            preserve_default=False,
        ),
    ]
