# Generated by Django 5.2.9 on 2026-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0008_envolvido_nr_documento_envolvido_tipo_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="antecedentes",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não"), ("I", "Não Informado")],
                default="I",
                max_length=1,
                verbose_name="Antec. Crim.",
            ),
        ),
        migrations.AlterField(
            model_name="envolvido",
            name="nr_documento",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Documento"
            ),
        ),
        migrations.AlterField(
            model_name="envolvido",
            name="tipo_documento",
            field=models.CharField(
                choices=[("1", "RG"), ("2", "CPF")], max_length=1, verbose_name="Tipo"
            ),
        ),
    ]
