# Generated by Django 5.2.9 on 2026-01-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0009_alter_envolvido_antecedentes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="tipo_participante",
            field=models.CharField(
                choices=[
                    ("V", "Vítima"),
                    ("A", "Autor"),
                    ("M", "Menor Infrator"),
                    ("P", "Preso"),
                    ("T", "Testemunha"),
                    ("S", "Suspeito"),
                ],
                max_length=1,
                verbose_name="Tipo",
            ),
        ),
    ]
