# Generated by Django 5.2.9 on 2026-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0010_alter_envolvido_tipo_participante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="antecedentes",
            field=models.CharField(
                choices=[("S", "Sim"), ("N", "Não"), ("I", "N/D")],
                default="I",
                max_length=1,
                verbose_name="Antec. Crim.",
            ),
        ),
    ]
