# Generated by Django 5.2.9 on 2026-01-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0011_alter_envolvido_antecedentes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envolvido",
            name="nr_documento",
            field=models.CharField(
                blank=True, max_length=14, null=True, verbose_name="Nr"
            ),
        ),
        migrations.AlterField(
            model_name="envolvido",
            name="tipo_documento",
            field=models.CharField(
                choices=[("1", "RG"), ("2", "CPF")],
                max_length=1,
                verbose_name="Documento",
            ),
        ),
    ]
