# Generated by Django 5.2.9 on 2026-01-18 00:10

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0013_alter_envolvido_antecedentes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalApreensao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Use vírgula para separar (Ex: 10.50 ou 1)",
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "unidade_medida",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Unidade de Medida"
                    ),
                ),
                (
                    "descricao_adicional",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Descrição Adicional",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material_tipo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.materialapreendidotipo",
                        verbose_name="Material Apreendido",
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Apreensão",
                "verbose_name_plural": "historical Apreensões",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEnvolvido",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("1", "RG"), ("2", "CPF")],
                        max_length=1,
                        verbose_name="Documento",
                    ),
                ),
                (
                    "nr_documento",
                    models.CharField(
                        blank=True, max_length=14, null=True, verbose_name="Nr"
                    ),
                ),
                (
                    "antecedentes",
                    models.CharField(
                        choices=[("S", "Sim"), ("N", "Não"), ("I", "N/D")],
                        default="I",
                        max_length=1,
                        verbose_name="Antec.",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "tipo_participante",
                    models.CharField(
                        choices=[
                            ("V", "Vítima"),
                            ("A", "Autor"),
                            ("M", "Menor Infrator"),
                            ("P", "Preso"),
                            ("T", "Testemunha"),
                            ("S", "Suspeito"),
                        ],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("idade", models.PositiveIntegerField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ocorrencia",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.ocorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Envolvido",
                "verbose_name_plural": "historical Envolvidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInstrumento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(db_index=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Instrumento",
                "verbose_name_plural": "historical Instrumentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMaterialApreendidoTipo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Tipo de Material"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tipo de Material Apreendido",
                "verbose_name_plural": "historical Tipos de Materiais Apreendidos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOcorrencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(
                        choices=[("C", "Consumado"), ("T", "Tentado")],
                        default="C",
                        max_length=1,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "data_hora_bruta",
                    models.CharField(
                        blank=True,
                        help_text="Formato DDHHMMMESAA (Ex: 151435DEZ25)",
                        max_length=15,
                        null=True,
                        verbose_name="Data/Hora Customizada",
                    ),
                ),
                (
                    "data_hora_fato",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Hora do Fato (DB)"
                    ),
                ),
                (
                    "relato_historico",
                    models.TextField(blank=True, verbose_name="Histórico Detalhado"),
                ),
                (
                    "resumo_cabecalho",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Resumo para Sumário"
                    ),
                ),
                (
                    "rua",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Rua/Via"
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "bairro",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Bairro"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrumento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.instrumento",
                        verbose_name="Instrumento utilizado (para CVLI)",
                    ),
                ),
                (
                    "natureza",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.naturezaocorrencia",
                    ),
                ),
                (
                    "opm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.opm",
                        verbose_name="OPM do Fato",
                    ),
                ),
                (
                    "relatorio_diario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rpi.relatoriodiario",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ocorrência",
                "verbose_name_plural": "historical Ocorrências",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRelatorioDiario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nr_relatorio",
                    models.PositiveIntegerField(verbose_name="Número do Relatório"),
                ),
                (
                    "ano_criacao",
                    models.PositiveIntegerField(verbose_name="Ano de Criação"),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Início do Período (24h)"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fim do Período (24h)"
                    ),
                ),
                ("data_criacao", models.DateTimeField(blank=True, editable=False)),
                (
                    "finalizado",
                    models.BooleanField(
                        default=False, verbose_name="Relatório Finalizado"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_responsavel",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Relatório Diário",
                "verbose_name_plural": "historical Relatórios Diários",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
