# Generated by Django 5.2.9 on 2026-01-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0015_historicalmunicipio_historicalnaturezaocorrencia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditCleanupLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("records_deleted", models.PositiveIntegerField()),
                ("status", models.CharField(default="Sucesso", max_length=20)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Log de Limpeza de Auditoria",
                "ordering": ["-executed_at"],
            },
        ),
    ]
