# Generated by Django 5.2.9 on 2026-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi", "0016_auditcleanuplog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnaturezaocorrencia",
            name="nome",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Fato"),
        ),
        migrations.AlterField(
            model_name="naturezaocorrencia",
            name="nome",
            field=models.CharField(max_length=255, unique=True, verbose_name="Fato"),
        ),
    ]
